### PR TITLE
Update to julia 1.1

### PR DESCRIPTION
**Pull request by davidanthoff**
Should only be merged once https://github.com/jupyter/repo2docker/pull/595 has shipped.

### CODE REVIEW

**Comment by choldgraf** [comment]
@davidanthoff just realized that the r2d PR was merged...is this ready to go?

**Comment by davidanthoff** [comment]
I think so. I'm not sure the r2d stuff has been deployed to binder or not (I don't fully understand that part of the project), but other than that it should be ready.

**Comment by choldgraf** [comment]
ah good point - I think you're right, we haven't bumped repo2docker on mybinder.org in a little bit...I see in that PR you mentioned a few things you thought might need to be tackled before the new r2d is deployed...any update on those? I'm happy to step you through a r2d bump on mybinder.org if you'd like to give that a shot! (it's just a PR to the mybinder.org-deploy repo)

**Comment by davidanthoff** [comment]
I think we should first merge https://github.com/jupyter/repo2docker/pull/622, then fixup and merge https://github.com/jupyter/repo2docker/pull/612, and then deploy a new version.

**Comment by choldgraf** [comment]
sounds good, will leave this one open then, thanks for following up :-)

**Comment by betatim** [comment]
I deployed a new version of repo2docker just now as we hadn't deployed since some time in February. Now looking at the other PRs and we can deploy again.

**Comment by betatim** [comment]
Merged this as well so I can test the repo2docker we just deployed.

**Comment by choldgraf** [comment]
wahoo!

**Pull request merged**
